#Build image base on base image
FROM golang:1.19-alpine

#Run: dùng để thực thi một câu lệnh trong images
RUN mkdir /app

#Copy all files from project to images
COPY ./ /app/

#Set working directory
WORKDIR /app/

#Cài đặt các dependencies cho project
RUN go mod download

#Buid project
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o go-airbnb .

EXPOSE 8080 8080

ENTRYPOINT ["/app/go-airbnb"]