app:
  Version: 1.0.0
  Port: 8080
  Mode: development
  Secret: 109339Lam
mysql:
  Host: localhost
  Port: 3307
  User: root
  Password: 109339Lam@
  DBName: go-airbnb

aws:
  Region: ap-southeast-1
  APIKey: AKIAXFND7G2RDKLZP6WM
  SecretKey: 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
  S3Domain: d24vk7oviyillz.cloudfront.net
  S3Bucket: lamhieogo