

name: Go

on:
  pull_request:
    branches: [ "develop" ]
    types:
        - closed
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Login to AWS ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region  ${{ secrets.AWS_REGION }}
        aws configure set default.output json
        aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 492654507682.dkr.ecr.ap-southeast-1.amazonaws.com
    
    - name: Build and push Docker image
      run: |
        docker build -t airbnb-cyber-api .
        docker tag airbnb-cyber-api:latest ${{ secrets.AWS_ECR_IMAGE }}
        docker push ${{ secrets.AWS_ECR_IMAGE }}
    
    - name: Deploy to Server EC2
      uses: appleboy/ssh-action@master
      with: 
        host: ec2-18-143-177-103.ap-southeast-1.compute.amazonaws.com 
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo su
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker run --name AppBE -d -p 8080:8080 ${{ secrets.AWS_ECR_IMAGE }}
