name: CI/CD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Build and push frontend image
#        if: github.event.pull_request.merged && startsWith(github.head_ref, 'frontend')
#        env:
#          DOCKERHUB_USERNAME: ${{ secrets.lamnguyen0206 }}
#          DOCKERHUB_PASSWORD: ${{ secrets.109339Lam@ }}
#        run: |
#          cd frontend
#          docker build -t lamnguyen0206/frontend:latest .
#          docker login -u lamnguyen0206 -p 109339Lam@
#          docker push lamnguyen0206/frontend:latest
      - name: Build and push backend image
        if: github.event.pull_request.merged && startsWith(github.head_ref, 'backend')
        env:
          DOCKERHUB_USERNAME: lamnguyen0206
          DOCKERHUB_PASSWORD: 109339Lam@
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/backend:latest .
          docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ env.DOCKERHUB_PASSWORD }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/backend:latest
